@WatchMatchApi_HostAddress = http://localhost:5099

POST {{WatchMatchApi_HostAddress}}/api/room/
Accept: application/json
Content-Type: application/json

"testId"
###

GET https://localhost:7272/api/room/
Accept: application/json
Content-Type: application/json

"testId"
